name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v3
        - name: check version
          run: xcodebuild -scheme Galla -showdestinations
        - name: run clean build
          run: xcodebuild clean build -scheme Galla -destination "platform=iOS Simulator,name=Any iOS Device,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        - name: run test
          run: xcodebuild test -scheme Galla -destination "platform=iOS Simulator,name=Any iOS Device,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
